image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
variables:
  TF_ROOT: ${CI_PROJECT_DIR}

  #change state name at the last of URL according to the environment...
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/wazuh
  

cache:
  key: dev
  paths:
    - ${TF_ROOT}/.terraform

before_script:
  - cd ${TF_ROOT}


stages:
  - install
  

####################
# DEV environment
####################  



Dev:install:
  stage: install
  environment:
    name: Wazuh
  before_script:
    - chmod 400 cloudstack-key
  script:
    - VM_IP=$(cat ip.txt)
    - chmod +x install_tool.sh
    - sleep 30s
    # - echo "" > ~/.ssh/known_hosts
    - ssh -i cloudstack-key -oStrictHostKeyChecking=no -t ubuntu@${VM_IP}<install_tool.sh
    

    - scp -i cloudstack-key -oStrictHostKeyChecking=no ubuntu@${VM_IP}:~/elastic_creds.txt ${TF_ROOT}/elastic_creds.txt
  tags:
    - "terraform"
  when: manual
  artifacts:
    paths:
      - ${TF_ROOT}/elastic_creds.txt

  needs:
    - project: soc/siem-and-xdr
      job: Dev:apply
      ref: wazuh-s100
      artifacts: true
