image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
variables:
  TF_ROOT: ${CI_PROJECT_DIR}

  #change state name at the last of URL according to the environment...
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/dev
  

cache:
  key: dev
  paths:
    - ${TF_ROOT}/.terraform

before_script:
  - cd ${TF_ROOT}


stages:
  - validate
  - build
  - deploy
  - install
  - destroy

####################
# DEV environment
####################  

Dev:validate:
  stage: validate
  environment:
    name: Dev

  script:      
    - test
    - gitlab-terraform init
    - gitlab-terraform validate
    
  tags:
    - "terraform"  
  only:
    variables:
      - $TRIGGER_JOB == "validate" 

Dev:plan:
  stage: build
  environment:
    name: Dev 
  script:
    - gitlab-terraform plan 
    - gitlab-terraform plan-json
   
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json
  tags:
    - "terraform" 
  when: manual
       

# Separate apply job for manual launching Terraform as it can be destructive
# action.
Dev:apply:
  stage: deploy
  environment:
    name: Dev
  script:
    - pwd artifacts.zip
    - gitlab-terraform apply
    - gitlab-terraform output -raw ip>ip.txt 
  artifacts:
    paths:
      - ip.txt   
  dependencies:
    - Dev:plan
  when: manual
  
  tags:
    - "terraform"

Dev:install:
  stage: install
  environment:
    name: Dev
  before_script:
    - chmod 400 cloudstack-key
  script:
    - VM_IP=$(cat ip.txt)
    - chmod +x install_tool.sh
    - sleep 30s
    - echo "" > ~/.ssh/known_hosts
    - ssh -i cloudstack-key -oStrictHostKeyChecking=no -t ubuntu@${VM_IP}<install_tool.sh
    - sudo scp -i cloudstack-key -oStrictHostKeyChecking=no ubuntu@${VM_IP}:~/wazuh_credentials.txt ${TF_ROOT}/wazuh_credentials.txt
  tags:
    - "shell"
  dependencies:
    - Dev:apply
  # needs:
  #   - project: soc/siem-and-xdr
  #     job: Dev:apply
  #     ref: wazuh-s100
  #     artifacts: true
  when: manual
  artifacts:
    paths:
      - ${TF_ROOT}/wazuh_credentials.txt

Dev:destroy:
  stage: destroy
  environment:
    name: Dev
  script:   
    - gitlab-terraform destroy
  dependencies:
    - Dev:plan
    - Dev:apply
  when: manual
 
  tags:
    - "terraform"      
